// flow-typed signature: f59c14f7174386e58cfc22f091e9aa2f
// flow-typed version: <<STUB>>/consign_v^0.1.6/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'consign'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'consign' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'consign/examples/express/api/middleware/application' {
  declare module.exports: any;
}

declare module 'consign/examples/express/api/middleware/user' {
  declare module.exports: any;
}

declare module 'consign/examples/express/api/models/user' {
  declare module.exports: any;
}

declare module 'consign/examples/express/api/routers/user' {
  declare module.exports: any;
}

declare module 'consign/examples/express/app' {
  declare module.exports: any;
}

declare module 'consign/examples/middleware-chain/app' {
  declare module.exports: any;
}

declare module 'consign/examples/middleware-chain/middleware/one' {
  declare module.exports: any;
}

declare module 'consign/examples/middleware-chain/middleware/three' {
  declare module.exports: any;
}

declare module 'consign/examples/middleware-chain/middleware/two' {
  declare module.exports: any;
}

declare module 'consign/examples/mvc/app' {
  declare module.exports: any;
}

declare module 'consign/examples/mvc/controllers/user' {
  declare module.exports: any;
}

declare module 'consign/examples/mvc/models/user' {
  declare module.exports: any;
}

declare module 'consign/lib/consign' {
  declare module.exports: any;
}

declare module 'consign/test/config' {
  declare module.exports: any;
}

declare module 'consign/test/exclude' {
  declare module.exports: any;
}

declare module 'consign/test/include' {
  declare module.exports: any;
}

declare module 'consign/test/into' {
  declare module.exports: any;
}

declare module 'consign/test/locale' {
  declare module.exports: any;
}

declare module 'consign/test/test-app/controllers/one' {
  declare module.exports: any;
}

declare module 'consign/test/test-app/controllers/three' {
  declare module.exports: any;
}

declare module 'consign/test/test-app/controllers/two' {
  declare module.exports: any;
}

declare module 'consign/test/test-app/models/one' {
  declare module.exports: any;
}

declare module 'consign/test/test-app/models/three' {
  declare module.exports: any;
}

declare module 'consign/test/test-app/models/two' {
  declare module.exports: any;
}

declare module 'consign/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'consign/examples/express/api/middleware/application.js' {
  declare module.exports: $Exports<'consign/examples/express/api/middleware/application'>;
}
declare module 'consign/examples/express/api/middleware/user.js' {
  declare module.exports: $Exports<'consign/examples/express/api/middleware/user'>;
}
declare module 'consign/examples/express/api/models/user.js' {
  declare module.exports: $Exports<'consign/examples/express/api/models/user'>;
}
declare module 'consign/examples/express/api/routers/user.js' {
  declare module.exports: $Exports<'consign/examples/express/api/routers/user'>;
}
declare module 'consign/examples/express/app.js' {
  declare module.exports: $Exports<'consign/examples/express/app'>;
}
declare module 'consign/examples/middleware-chain/app.js' {
  declare module.exports: $Exports<'consign/examples/middleware-chain/app'>;
}
declare module 'consign/examples/middleware-chain/middleware/one.js' {
  declare module.exports: $Exports<'consign/examples/middleware-chain/middleware/one'>;
}
declare module 'consign/examples/middleware-chain/middleware/three.js' {
  declare module.exports: $Exports<'consign/examples/middleware-chain/middleware/three'>;
}
declare module 'consign/examples/middleware-chain/middleware/two.js' {
  declare module.exports: $Exports<'consign/examples/middleware-chain/middleware/two'>;
}
declare module 'consign/examples/mvc/app.js' {
  declare module.exports: $Exports<'consign/examples/mvc/app'>;
}
declare module 'consign/examples/mvc/controllers/user.js' {
  declare module.exports: $Exports<'consign/examples/mvc/controllers/user'>;
}
declare module 'consign/examples/mvc/models/user.js' {
  declare module.exports: $Exports<'consign/examples/mvc/models/user'>;
}
declare module 'consign/index' {
  declare module.exports: $Exports<'consign'>;
}
declare module 'consign/index.js' {
  declare module.exports: $Exports<'consign'>;
}
declare module 'consign/lib/consign.js' {
  declare module.exports: $Exports<'consign/lib/consign'>;
}
declare module 'consign/test/config.js' {
  declare module.exports: $Exports<'consign/test/config'>;
}
declare module 'consign/test/exclude.js' {
  declare module.exports: $Exports<'consign/test/exclude'>;
}
declare module 'consign/test/include.js' {
  declare module.exports: $Exports<'consign/test/include'>;
}
declare module 'consign/test/into.js' {
  declare module.exports: $Exports<'consign/test/into'>;
}
declare module 'consign/test/locale.js' {
  declare module.exports: $Exports<'consign/test/locale'>;
}
declare module 'consign/test/test-app/controllers/one.js' {
  declare module.exports: $Exports<'consign/test/test-app/controllers/one'>;
}
declare module 'consign/test/test-app/controllers/three.js' {
  declare module.exports: $Exports<'consign/test/test-app/controllers/three'>;
}
declare module 'consign/test/test-app/controllers/two.js' {
  declare module.exports: $Exports<'consign/test/test-app/controllers/two'>;
}
declare module 'consign/test/test-app/models/one.js' {
  declare module.exports: $Exports<'consign/test/test-app/models/one'>;
}
declare module 'consign/test/test-app/models/three.js' {
  declare module.exports: $Exports<'consign/test/test-app/models/three'>;
}
declare module 'consign/test/test-app/models/two.js' {
  declare module.exports: $Exports<'consign/test/test-app/models/two'>;
}
declare module 'consign/test/tests.js' {
  declare module.exports: $Exports<'consign/test/tests'>;
}
